name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Build Directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -B build -S .
        shell: bash

      - name: Build
        run: cmake --build build --config Release
        shell: bash

      - name: Test
        working-directory: build
        run: ctest --build-config Release
        shell: bash